=== malesevicluka/OR/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://example.com/example.json",
    "type": "array",
    "default": [],
    "title": "Root Schema",
    "items": {
        "type": "object",
        "title": "A Schema",
        "required": [
            "Naziv",
            "Adresa",
            "Kvart",
            "Kapacitet",
            "Facebook",
            "Instagram",
            "Kontakt",
            "Recenzija",
            "Minimalna_dob_ulaza",
            "Radno_vrijeme"
        ],
        "properties": {
            "Naziv": {
                "type": "string",
                "title": "The Naziv Schema"
            },
            "Adresa": {
                "type": "string",
                "title": "The Adresa Schema"
            },
            "Kvart": {
                "type": "string",
                "title": "The Kvart Schema"
            },
            "Kapacitet": {
                "type": "integer",
                "title": "The Kapacitet Schema"
            },
            "Facebook": {
                "type": "string",
                "title": "The Facebook Schema"
            },
            "Instagram": {
                "type": "string",
                "title": "The Instagram Schema"
            },
            "Kontakt": {
                "type": "string",
                "title": "The Kontakt Schema"
            },
            "Recenzija": {
                "type": "integer",
                "title": "The Recenzija Schema"
            },
            "Minimalna_dob_ulaza": {
                "type": "integer",
                "title": "The Minimalna_dob_ulaza Schema"
            },
            "Radno_vrijeme": {
                "type": "array",
                "title": "The Radno_vrijeme Schema",
                "items": {
                    "type": "object",
                    "title": "A Schema",
                    "required": [
                        "Dan",
                        "Otvaranje",
                        "Zatvaranje"
                    ],
                    "properties": {
                        "Dan": {
                            "type": "string",
                            "title": "The Dan Schema"
                        },
                        "Otvaranje": {
                            "type": "string",
                            "title": "The Otvaranje Schema"
                        },
                        "Zatvaranje": {
                            "type": "string",
                            "title": "The Zatvaranje Schema"
                        }
                    }
                }
            }
        }
    }
}

=== malesevicluka/OR/public/nightclubs.json
[
    {
        "Naziv": "EX. club",
        "Adresa": "Izidora Kršnjavoga 1",
        "Kvart": "Trešnjevka",
        "Kapacitet": 700,
        "Facebook": "EX. club",
        "Instagram": "ex.club_",
        "Kontakt": "0991629634",
        "Recenzija": 4,
        "Minimalna_dob_ulaza": 21,
        "Radno_vrijeme": [
            {
                "Dan": "petak",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "06:00:00"
            },
            {
                "Dan": "subota",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "06:00:00"
            }
        ]
    },
    {
        "Naziv": "The Secret club",
        "Adresa": "Draškovićeva ul. 41",
        "Kvart": "Donji grad",
        "Kapacitet": 600,
        "Facebook": "The Secret Club",
        "Instagram": "thesecretclub.zagreb",
        "Kontakt": "0997327389",
        "Recenzija": 3,
        "Minimalna_dob_ulaza": 21,
        "Radno_vrijeme": [
            {
                "Dan": "petak",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "05:00:00"
            },
            {
                "Dan": "subota",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "05:00:00"
            }
        ]
    },
    {
        "Naziv": "XO club",
        "Adresa": "Vlaška ul. 9",
        "Kvart": "Donji grad",
        "Kapacitet": 550,
        "Facebook": "XO Club",
        "Instagram": "xo.club.zg",
        "Kontakt": "0953823998",
        "Recenzija": 4,
        "Minimalna_dob_ulaza": 18,
        "Radno_vrijeme": [
            {
                "Dan": "petak",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "05:00:00"
            },
            {
                "Dan": "subota",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "05:00:00"
            }
        ]
    },
    {
        "Naziv": "H2O",
        "Adresa": "Ulica Josipa Runjanina 3",
        "Kvart": "Donji grad",
        "Kapacitet": 700,
        "Facebook": "Club H2O",
        "Instagram": "clubh2ozagreb",
        "Kontakt": "0915100661",
        "Recenzija": 3,
        "Minimalna_dob_ulaza": 18,
        "Radno_vrijeme": [
            {
                "Dan": "petak",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "05:00:00"
            },
            {
                "Dan": "subota",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "05:00:00"
            }
        ]
    },
    {
        "Naziv": "Club Roko",
        "Adresa": "Jarunska ul. 5",
        "Kvart": "Jarun",
        "Kapacitet": 1000,
        "Facebook": "Club Roko",
        "Instagram": "club.roko",
        "Kontakt": "0976592000",
        "Recenzija": 4,
        "Minimalna_dob_ulaza": 18,
        "Radno_vrijeme": [
            {
                "Dan": "srijeda",
                "Otvaranje": "22:00:00",
                "Zatvaranje": "04:00:00"
            },
            {
                "Dan": "petak",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "04:00:00"
            },
            {
                "Dan": "subota",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "04:00:00"
            }
        ]
    },
    {
        "Naziv": "BBS",
        "Adresa": "Remetinečka cesta 11",
        "Kvart": "Kajzerica",
        "Kapacitet": 600,
        "Facebook": "Night Club BBS",
        "Instagram": "bbsnightclub",
        "Kontakt": "0953333123",
        "Recenzija": 3,
        "Minimalna_dob_ulaza": 21,
        "Radno_vrijeme": [
            {
                "Dan": "srijeda",
                "Otvaranje": "22:00:00",
                "Zatvaranje": "05:00:00"
            },
            {
                "Dan": "petak",
                "Otvaranje": "22:00:00",
                "Zatvaranje": "05:00:00"
            },
            {
                "Dan": "subota",
                "Otvaranje": "22:00:00",
                "Zatvaranje": "05:00:00"
            }
        ]
    },
    {
        "Naziv": "OUT Bunker",
        "Adresa": "Ilica 16",
        "Kvart": "Centar",
        "Kapacitet": 400,
        "Facebook": "OUT Bunker",
        "Instagram": "outbunker",
        "Kontakt": "0981600123",
        "Recenzija": 4,
        "Minimalna_dob_ulaza": 18,
        "Radno_vrijeme": [
            {
                "Dan": "ponedjeljak",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "04:00:00"
            },
            {
                "Dan": "utorak",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "04:00:00"
            },
            {
                "Dan": "srijeda",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "04:00:00"
            },
            {
                "Dan": "četvrtak",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "04:00:00"
            },
            {
                "Dan": "petak",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "05:00:00"
            },
            {
                "Dan": "subota",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "05:00:00"
            }
        ]
    },
    {
        "Naziv": "Mint",
        "Adresa": "Ul. Florijana Andrašeca 14",
        "Kvart": "Trešnjevka",
        "Kapacitet": 600,
        "Facebook": "MINT club & more",
        "Instagram": "mintzagreb",
        "Kontakt": "mintclub.hr",
        "Recenzija": 4,
        "Minimalna_dob_ulaza": 21,
        "Radno_vrijeme": [
            {
                "Dan": "srijeda",
                "Otvaranje": "22:00:00",
                "Zatvaranje": "03:00:00"
            },
            {
                "Dan": "petak",
                "Otvaranje": "21:00:00",
                "Zatvaranje": "04:00:00"
            },
            {
                "Dan": "subota",
                "Otvaranje": "21:00:00",
                "Zatvaranje": "04:00:00"
            }
        ]
    },
    {
        "Naziv": "Katran",
        "Adresa": "Radnička cesta 27",
        "Kvart": "Trnje",
        "Kapacitet": 950,
        "Facebook": "Katran Zagreb",
        "Instagram": "katranzagreb",
        "Kontakt": "",
        "Recenzija": 4,
        "Minimalna_dob_ulaza": 18,
        "Radno_vrijeme": [
            {
                "Dan": "petak",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "05:00:00"
            },
            {
                "Dan": "subota",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "05:00:00"
            }
        ]
    },
    {
        "Naziv": "Ritz",
        "Adresa": "Ul. Florijana Andrašeca 14",
        "Kvart": "Trešnjevka",
        "Kapacitet": 800,
        "Facebook": "Ritz Club",
        "Instagram": "ricklubzg",
        "Kontakt": "0913551355",
        "Recenzija": 3,
        "Minimalna_dob_ulaza": 21,
        "Radno_vrijeme": [
            {
                "Dan": "petak",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "05:00:00"
            },
            {
                "Dan": "subota",
                "Otvaranje": "23:00:00",
                "Zatvaranje": "05:00:00"
            }
        ]
    }
]
